name: Update Profile

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
        - name: Generate snake game .svg
          uses: Platane/snk@v2
          with:
            # github user name to read the contribution graph from (**required**)
            # using action context var `github.repository_owner` or specified user
            github_user_name: ${{ github.repository_owner }}

            # list of files to generate.
            # one file per line. Each output can be customized with options as query string.
            #
            #  supported options:
            #  - palette:     A preset of color, one of [github, github-dark, github-light]
            #  - color_snake: Color of the snake
            #  - color_dots:  Coma separated list of dots color.
            #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
            #                 Exactly 5 colors are expected.
            outputs: |
              dist/github-snake-light.svg?palette=github-light
              dist/github-snake-dark.svg?palette=github-dark
              
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
        - name: Push snake game .svg to output branch
          uses: crazy-max/ghaction-github-pages@v2.6.0
          with:
            target_branch: output
            build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
